### ISSUE TITLE
Plans for new release?

### ISSUE THREAD

**Issue by reta** [xebialabs/overcast#17]
Hey guys!

Any plans for new minor release? Quite a few features have been introduced :)
Thanks!

Best Regards,
    Andriy Redko

**Comment by rklaren** [comment]
Would love to do a new release. Only have to figure out a scope. 

Ideally I would like to upgrade various libraries we use to interface to things (docker/ec2/libvirt). Had started on that but ran into something. So will probably do a less ambitious release somewhere. It may be a few weeks though before I have time to verify that all the integration tests work (moving to a new building with the company/holidays/etc). 

At some point this year I'll be reworking the libvirt stuff to be compatible with new versions of libvirt (we use that extensively in the company) so that will be in company time. A lot of other stuff can piggy back on that work. So somewhere after summer a bigger release is coming.

Cheers,

Ric

**Comment by reta** [comment]
Hi Ric,

Awesome, thanks a lot for this roadmap, sounds like a great plan, thanks a lot for spending your time on the project.  Thanks!

Best Regards,
    Andriy Redko
